Fix php8 compatibility
pickware/ShopwareStripePayment pull request #114
Opened 2022-03-29 15:05 UTC by JanRogge

`array_key_exists` only works on arrays with PHP8 which results in errors when the order gets canceled with a creditcard. But for our case of just checking if the property is there we can use `property_exists` on the ArrayObject which exists sind PHP 5.1.

2022-03-29 15:55 UTC, svenmuennich requested changes

2022-03-29 15:55 UTC, svenmuennich commented on Util.php
> +        $hasSaveCardForFutureCheckouts = property_exists($session, 'saveCardForFutureCheckouts');
So `$session` is not an array but an object? Do we have other usages of that object where we treat it like an array?

2022-04-04 10:10 UTC, JanRogge commented on Util.php
> +        $hasSaveCardForFutureCheckouts = property_exists($session, 'saveCardForFutureCheckouts');
Yes `stripePayment` is an ArrayObject. Everything else looks fine `array_key_exists` deprecated the support of objects with 7.4 and since 8.0 it results in an error.

2022-04-05 06:08 UTC, svenmuennich approved these changes

2022-04-05 06:10 UTC, merged