Fix payments not possible via digital wallets when customer address is in a country other than the stripe account
pickware/ShopwareStripePayment pull request #95
Opened 2021-04-27 12:50 UTC by JanRogge

**Summary**

Currently for StripePayments we use the country code of the customer which is wrong since it needs to be the country code which is set in the stripe account.
When updating the plugin we use the last 2 digits of the ISO Code from the default shops localization as a default stripe account country code. This will be updated to the country code of the stripe account if the stripe config gets saved with a valid secret key. 

Closes #93

2021-05-03 11:56 UTC, felixbrucker requested changes
Nice work!

2021-05-03 11:56 UTC, felixbrucker commented on Bootstrap.php
> +use Shopware\Models\Config\Form;
```suggestion
```

2021-05-03 11:56 UTC, felixbrucker commented on Bootstrap.php
> +                        'SELECT locale FROM s_core_locales l JOIN s_core_shops s ON s.locale_id = l.id WHERE s.default = 1'
```suggestion
                        'SELECT locale.locale
                        FROM s_core_locales locale
                        JOIN s_core_shops shop ON shop.locale_id = locale.id
                        WHERE shop.default = 1'
```

2021-05-03 11:56 UTC, felixbrucker commented on CHANGELOG.md
> +* Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differed.
```suggestion
* Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differ.
```

2021-05-03 11:56 UTC, felixbrucker commented on Subscriber/Backend/ConfigSubscriber.php
> +     * Handle the retriving of the stripe account country and saving it to a hidden config value
```suggestion
     * Handle the retrieving of the stripe account country and saving it to a hidden config value
```

2021-05-03 11:56 UTC, felixbrucker commented on Subscriber/Backend/ConfigSubscriber.php
> +
```suggestion
```

2021-05-03 11:56 UTC, felixbrucker commented on Subscriber/Backend/ConfigSubscriber.php
> +
```suggestion
```

2021-05-03 11:56 UTC, felixbrucker commented on Subscriber/Backend/ConfigSubscriber.php
> +        $secretKey  = Util::stripeSecretKey();
```suggestion
        $secretKey = Util::stripeSecretKey();
```

2021-05-03 11:56 UTC, felixbrucker commented on Util.php
> +    public static function getAccount()
```suggestion
    public static function getStripeAccount()
```

2021-05-03 11:56 UTC, felixbrucker commented on Bootstrap.php
> +
```suggestion
```

2021-05-04 10:20 UTC, felixbrucker requested changes
Almost there!

2021-05-04 10:20 UTC, felixbrucker commented on Bootstrap.php
> +                }
You'll want to add `'proxy',` to the list of `invalidateCache`s below at the end of this method, so that the subscriber works out of the box.

2021-05-04 10:20 UTC, felixbrucker commented on Subscriber/Backend/ConfigSubscriber.php
> +        if ($data[0]['name'] !== 'stripeSecretKey') {
This feels more robust than checking the first key of the elements to save

2021-05-04 11:36 UTC, felixbrucker approved these changes
LGTM

2021-05-07 09:01 UTC, svenmuennich approved these changes

2021-05-07 09:02 UTC, merged