Clear one time credit cards from session after failed checkout
pickware/ShopwareStripePayment pull request #96
Opened 2021-05-10 07:59 UTC by JanRogge

Currently when a payment with a credit card fails we redirect to the checkout with the last selected card still selected.
This is a problem if the last card was a one time use card since it will not work anymore.

This PR changes this by removing one time credit cards from the session after a failed checkout.

Fixes #91

2021-05-10 13:37 UTC, felixbrucker requested changes
Nice work!

2021-05-10 13:37 UTC, felixbrucker commented on Util.php
> +    public static function removeNotSavedCardFromSession()
```suggestion
    public static function removeUnsavedSelectedCardFromSession()
```

2021-05-10 13:37 UTC, felixbrucker commented on Util.php
> +        $saveCardForFutureCheckouts = array_key_exists('saveCardForFutureCheckouts', $session);
```suggestion
        $hasSaveCardForFutureCheckouts = array_key_exists('saveCardForFutureCheckouts', $session);
```

2021-05-10 13:37 UTC, felixbrucker commented on Util.php
> +            $session->selectedCard = [];
Why dont we `unset()` the selected card here?

2021-05-10 13:37 UTC, felixbrucker commented on CHANGELOG.md
> +* Behebt einen Fehler, der dazu führte, dass nicht gespeicherte Kreditkarten bei einem fehlerhaften Bestellabschluss weiterhin angezeigt wurden.
```suggestion
* Behebt einen Fehler, der dazu führte, dass nicht gespeicherte Kreditkarten nach einem fehlgeschlagenen Bestellabschluss weiterhin angezeigt wurden.
```

2021-05-10 13:37 UTC, felixbrucker commented on CHANGELOG.md
> +* Fixes a bug that caused unsaved credit cards to continue to display when an order was completed incorrectly.
```suggestion
* Fixes a bug that caused unsaved credit cards to continue to be displayed after a failed order completion.
```

2021-05-14 07:00 UTC, felixbrucker approved these changes
LGTM

2021-05-17 07:57 UTC, svenmuennich approved these changes

2021-05-17 07:58 UTC, merged